// generated by unplugin-vue-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DropdownMenu: typeof import('./views/DropdownMenu.vue')['default']
    Item: typeof import('./views/Item.vue')['default']
    'Mdi:bookmark': typeof import('~icons/mdi/bookmark')['default']
    'Mdi:bookmarkOutline': typeof import('~icons/mdi/bookmark-outline')['default']
    MdiMicrosoftVisualStudioCode: typeof import('~icons/mdi/microsoft-visual-studio-code')['default']
    Repos: typeof import('./views/Repos.vue')['default']
  }
}

export { }
